export const mazes = [
  // {
  //   id: 0,
  //   name: "Level 1",
  //   maze: [
  //     "WWWWWWWWWWWWWWWWWWWWW",
  //     "W........W..........XW",
  //     "W.WWWWW..W..WWWWWWWW.W",
  //     "W.W....W.....W....W..W",
  //     "W.WWW.WW.WWWW.W.WWW.WW",
  //     "W....W.......W.W.....W",
  //     "W.WWWWWWW.WWWWWWWWW..W",
  //     "W.W..............W..WW",
  //     "W.W.WWWWWWWWWW.WWW...W",
  //     "W.W......W....W..W.W.W",
  //     "W.WWWWW..W..WWWWWW.W.W",
  //     "W........W........W..W",
  //     "WWWWWWWWWWWWWWWWWWWWWW",
  //   ],
  // },
  {
    id: 0,
    name: "Level 1",
    maze: ["WWWW", "WX.W", "W..W", "WY.W", "WWWW"],
  },
  {
    id: 1,
    name: "Level 2",
    maze: [
      "WWWWWWWWWWWWWWWWWWWWW",
      "W.....W....W.....W..W",
      "W.WWW.WWW.W.W.WWW.W.W",
      "W.W....W.W.W.W.WW.W.W",
      "W.WWW.W.W.WWW.W..W..W",
      "W.WW..W.......W.WWW.W",
      "W....WWWWWWWWW.W.W..W",
      "WWWWW.W.......W.WW..W",
      "W....W...WWW..W.WW..W",
      "W.WWWWW..W.W..W.WWWWW",
      "W.....W..W...W.....WW",
      "WXWW.WWWWW.WWWWWWWW.W",
      "WWWWWWWWWWWWWWWWWWWWW",
    ],
  },
  {
    id: 2,
    name: "Open Level",
    maze: [
      "WWWWWWWWWWWWWWWWWWWWW",
      "W...............X...W",
      "W.W.X....W..........W",
      "W.W..W...W...W...WW.W",
      "W....W..W....W......W",
      "W.W.....W...........W",
      "W.W.....W......W....W",
      "W.W............W....W",
      "W.W..W.....W..W...WWW",
      "W.W......W.....W....W",
      "W.WWWWWWWW...Y.WWWW.W",
      "W.................W.W",
      "WWWWWWWWWWWWWWWWWWWWW",
    ],
  },
  {
    id: 3,
    name: "Long Corridors Level",
    maze: [
      "WWWWWWWWWWWWWWWWWWWWWW",
      "W..................X.W",
      "WWWWWWWWWWWWWWWWWWW..W",
      "W....................W",
      "W.WWWWWWWWWWWWWWWWWW.W",
      "W....................W",
      "W..WWWWWWWWWWWWWWWWW.W",
      "W....................W",
      "WWWWWWWWWWWWWWWWW....W",
      "W..................W.W",
      "WWWWWWWWWWWWWW.......W",
      "W.................W..W",
      "WWWWWWWWWWWWWWWWWWWWWW",
    ],
  },
];
