import { characterCards } from "./characterChards";
import { ICard } from "./types";

// Define card templates using MTG-like structure
export const cardTypes: Omit<ICard, "id">[] = [
  {
    name: "Mountain",
    land: "mountain",
    type: "Land",
    description: "symbol-red",
    flavorText: "Chaos and fire reigns here.",
    rarity: "Common",
    value: 1,
  },
  {
    name: "Swamp",
    land: "swamp",
    type: "Land",
    description: "symbol-black",
    flavorText: "Desperation feeds the marshes...",
    rarity: "Common",
    value: 1,
  },
  {
    name: "Forest",
    land: "forest",
    type: "Land",
    description: "symbol-green",
    flavorText: "Where life grows, fights and survives.",
    rarity: "Common",
    value: 1,
  },
  {
    name: "Plains",
    land: "plains",
    type: "Land",
    description: "symbol-white",
    flavorText: "Justice and truth sweeps the plains.",
    rarity: "Common",
    value: 1,
  },
  {
    name: "Island",
    land: "island",
    type: "Land",
    description: "symbol-blue",
    flavorText: "Where cunning and mystery prevails.",
    rarity: "Common",
    value: 1,
  },
  {
    name: "City roamer",
    land: "plains",
    type: "Land",
    description: "Come ride the train, have some candies.",
    flavorText: "He feeds on the little children.",
    rarity: "Common",
    value: 1,
    power: 1,
    toughness: 1,
  },
  {
    name: "MOD",
    manaCost: "1R",
    land: "mountain",
    type: "Sorcery",
    subtype: "Brew",
    description:
      "Throw a dice, 1-3 gives you 10 life, 4-6 gives you 10 damage.",
    flavorText: "Fire in your belly, chaos in your mind.",
    rarity: "Rare",
    value: 10,
  },
  {
    name: "Beer Bear",
    manaCost: "4GGG",
    land: "forest",
    type: "Creature",
    subtype: "Bear",
    description:
      "Whenever Beer Bear attacks, it deals 15 damage to target opponent.",
    flavorText: "No one gets between a bear and its drink.",
    power: 4,
    toughness: 4,
    rarity: "Uncommon",
    value: 15,
  },
  {
    name: "Red red wine",
    manaCost: "R",
    land: "mountain",
    type: "Instant",
    description: "Gain 5 life, for now...",
    flavorText: "More wine, less problems.",
    rarity: "Uncommon",
    value: 10,
  },
  {
    name: "Meat Club",
    manaCost: "1R",
    land: "mountain",
    type: "Artifact",
    description: "Target creature gets +3/+0 and is indestructible this turn.",
    flavorText:
      "Dipped in Ice Cream, a bizarre delicacy with a surprisingly powerful punch.",
    rarity: "Uncommon",
    value: 12,
  },
  {
    name: "GRIS",
    manaCost: "3b",
    land: "swamp",
    type: "Creature",
    subtype: "Pig Athlete",
    description: "Whenever GRIS blocks, it gains +1/+1 until end of turn.",
    flavorText:
      "With a perfect serve and a snort of victory, it rules the court.",
    power: 1,
    toughness: 4,
    rarity: "Common",
    value: 8,
  },
  {
    name: "French Estate",
    manaCost: "WW",
    land: "plains",
    type: "Land",
    description:
      "Tap: Add one mana of any color. Sacrifice French Estate: Draw a card.",
    flavorText: "A symbol of grandeur, ripe for new possibilities.",
    rarity: "Rare",
    value: 18,
  },
  {
    name: "Salmon factory",
    manaCost: "1Bb",
    land: "swamp",
    type: "Artifact",
    description: "Tap: Sacrifice a creature and draw 4 cards.",
    flavorText: "In the pugnant depths, where boys toil, men ar produced...",
    rarity: "Rare",
    value: 18,
  },
  {
    name: "Fifa-rules",
    manaCost: "B",
    land: "island",
    type: "Instant",
    description:
      "Flip a coin, heads means you draw 2 cards, tails means your opponent will.",
    flavorText: "Go left or right...",
    rarity: "Rare",
    value: 18,
  },
  {
    name: "Klose",
    manaCost: "1WW",
    land: "plains",
    type: "Instant",
    description:
      "If Klose is killed, he attacks the player directly, bypassing any creatures in the way.",
    flavorText: "Don't bet against him, ever...",
    rarity: "Rare",
    value: 18,
    power: 4,
    toughness: 2,
  },
  {
    name: "Fiji time",
    manaCost: "BB",
    land: "island",
    type: "Instant",
    description:
      "When Fiji time is played, make all other cards inactive this turn.",
    flavorText: "The boat is here in 15 minutes or 15 hours, Fiji time!",
    rarity: "Common",
    value: 18,
  },
  {
    name: "Awesome possum",
    manaCost: "2B",
    land: "island",
    type: "Creature",
    subtype: "",
    description: "Fold to call upon another awesome possum.",
    flavorText: "Where there is one, there are more...",
    rarity: "Mythic Rare",
    value: 30,
    power: 1,
    toughness: 1,
  },
  {
    name: "Benzema",
    manaCost: "3WW",
    land: "plains",
    type: "Creature",
    subtype: "Legendary persuasion",
    description:
      "When Benzema enters the battlefield, gain control of target creature an opponent controls.",
    flavorText: "Simply say 'Benzema' and friends will gather.",
    rarity: "Mythic Rare",
    value: 30,
    power: 5,
    toughness: 2,
  },
  {
    name: "Curt Bergfors",
    manaCost: "2b",
    land: "swamp",
    type: "Creature",
    subtype: "Human Duo",
    description:
      "When Curt Bergfors and his gold-digger wife enters the battlefield, draw two cards and lose 4 life.",
    flavorText:
      "He may be fragile, but his hamburger fortune speaks louder than words.",
    power: 1,
    toughness: 3,
    rarity: "Rare",
    value: 14,
  },
  {
    name: "Katla",
    manaCost: "4bb",
    land: "swamp",
    type: "Creature",
    subtype: "Terrifying dragon",
    description:
      "When Katla enters the battlefield, each opponent must take one of their creatures of the field.",
    flavorText:
      "Risen from the depths of the netherworld, if you see her smoke you better run.",
    power: 4,
    toughness: 7,
    rarity: "Rare",
    value: 14,
  },
  {
    name: "The Guardians",
    manaCost: "WWW",
    land: "plains",
    type: "Creature",
    subtype: "Three musketeers",
    description: "Tap to heal 3 damage.",
    flavorText: "Securing the perimeter with a drunken eye, they wait.",
    power: 3,
    toughness: 3,
    rarity: "Rare",
    value: 14,
  },
  {
    name: "Bumper balls",
    manaCost: "Wb",
    land: "plains",
    type: "Enchantment",
    subtype: "",
    description: "All your creatures receive -2/+4.",
    flavorText: "They are fat, immobile and content.",
    rarity: "Rare",
    value: 14,
  },
  {
    name: "'Bile",
    manaCost: "2W",
    land: "plains",
    type: "Creature",
    subtype: "Slave",
    description: "Gain +1/+1 each time he is attacked.",
    flavorText: "Chained at the end of bad jokes, this one has had enough.",
    rarity: "Rare",
    value: 14,
    power: 1,
    toughness: 4,
  },
  {
    name: "Runners squad",
    manaCost: "2W",
    land: "plains",
    type: "Creature",
    subtype: "Hive mind",
    description:
      "Divide and conquer: by tapping runners squad can spread their damage across any number of creatures.",
    flavorText:
      "They may be separated by many leagues, but their mind is as one.",
    rarity: "Rare",
    value: 14,
    power: 3,
    toughness: 1,
  },
  {
    name: "Norwegian Ogre",
    manaCost: "1RR",
    land: "mountain",
    type: "Creature",
    subtype: "Terrifying dragon",
    description:
      "Can block any creatures attack, taking the full damage itself.",
    flavorText: "Jag e ikke ful!",
    power: 1,
    toughness: 5,
    rarity: "Rare",
    value: 14,
  },
  {
    name: "3-0",
    manaCost: "BBB",
    land: "island",
    type: "Instant",
    subtype: "Devious spell",
    description: "Counter any spell, draw 2 cards.",
    flavorText: "Nothing is more sacred than three straight wins.",
    rarity: "Rare",
    value: 14,
  },
  {
    name: "Tentstack",
    manaCost: "b",
    land: "swamp",
    type: "Instant",
    subtype: "",
    description: "Draw a card from the opponents deck.",
    flavorText: "Why is that tent full of chairs?",
    rarity: "Rare",
    value: 14,
  },
];

export const cards = [...cardTypes, ...characterCards];
